### PR TITLE
Added support of big endian platforms in generic64 target

### PR DESCRIPTION
**Pull request by nobody4t**
Signed-off-by: Gilles Van Assche <gva-github@noekeon.org>
Signed-off-by: Wang Dong <xdragon007@gmail.com>

### CODE REVIEW

**Comment by gvanas** [comment]
I would suggest to integrate the latest changes directly (see commit [c73713…](https://github.com/gvanas/KeccakCodePackage/commit/c737139c81fd191699886a9a74d3220f6e300b29)), but maybe that was your intention…

**Comment by WandyLau** [comment]
I have a look at the file, and there are some differences. So I just added the core part. I will have a try. If it is fine, I will integrate it directly.

**Comment by WandyLau** [comment]
@gvanas  That patch could not be applied directly. There are some different between them.

**Comment by gvanas** [comment]
I see. The file used in this project is fairly old.

**Comment by bjornedstrom** [comment]
Thank you, merged the patch.

**Pull request merged**
